updates

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -10,29 +10,55 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
+    - name: Use Node.js 12.x
+      uses: actions/setup-node@v4
       with:
         node-version: lts/*
-    - name: Install dependencies
-      run: npm ci
-    - name: Install Playwright Browsers
-      run: npx playwright install --with-deps
-
-    - name: Wait for Netlify Deployment
-      id: netlify
+    - name: Install
       run: |
-        echo "Waiting for Netlify deployment to complete..."
-        # Fetch Netlify deployment URL by querying Netlify's API, assuming you have NETLIFY_AUTH_TOKEN & NETLIFY_SITE_ID set in secrets
-        PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
-        DEPLOY_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" \
-                        https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys | \
-                        jq -r ".[0] | select(.title | index(\"pull/${PR_NUMBER}\")) | .deploy_ssl_url")
-        echo "Netlify deployment URL: $DEPLOY_URL"
-        echo "::set-output name=preview_url::$DEPLOY_URL"
+        npm ci
+    - name: Build
+      run: |
+        npm run build
+    - name: Waiting for 200 from the Netlify Preview
+      uses: kamranayub/wait-for-netlify-action@v2.1.0
+      id: wait-for-netflify-preview
+      with:
+        site_name: "YOUR_SITE_NAME"
+      env:
+        NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}
+    - name: Lighthouse CI
+      run: |
+        echo ${{ steps.wait-for-netflify-preview.outputs.url }}
+        npm install -g @lhci/cli@0.3.x
+        lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.wait-for-netflify-preview.outputs.url }} || echo "LHCI failed!"
+      env:
+        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+    # steps:
+    # - uses: actions/checkout@v4
+    # - uses: actions/setup-node@v4
+    #   with:
+    #     node-version: lts/*
+    # - name: Install dependencies
+    #   run: npm ci
+    # - name: Install Playwright Browsers
+    #   run: npx playwright install --with-deps
+
+    # - name: Wait for Netlify Deployment
+    #   id: netlify
+    #   run: |
+    #     echo "Waiting for Netlify deployment to complete..."
+    #     # Fetch Netlify deployment URL by querying Netlify's API, assuming you have NETLIFY_AUTH_TOKEN & NETLIFY_SITE_ID set in secrets
+    #     PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
+    #     DEPLOY_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" \
+    #                     https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys | \
+    #                     jq -r ".[0] | select(.title | index(\"pull/${PR_NUMBER}\")) | .deploy_ssl_url")
+    #     echo "Netlify deployment URL: $DEPLOY_URL"
+    #     echo "::set-output name=preview_url::$DEPLOY_URL"
 
 
-    - name: Run Playwright tests
-      run: npx playwright test --base-url=${{ steps.netlify.outputs.preview_url }}
+    # - name: Run Playwright tests
+    #   run: npx playwright test --base-url=${{ steps.netlify.outputs.preview_url }}
     - uses: actions/upload-artifact@v4
       if: always()
       with:
